version: '3'
services:
  mysql:
    image: mysql:5.7.27
    ports:
          - 3306:3306
    # volumes:
      # - ./master-scripts/:/docker-entrypoint-initdb.d/
      # - ./master.conf:/etc/mysql/conf.d/mysql.cnf
      # - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: "sample"
