version: '3'
services:
  mysql:
    image: mysql:5.7.27
    ports:
          - 3306:3306
    volumes:
      - ./schema.sql/:/docker-entrypoint-initdb.d/01_schema.sql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: "sample"
